using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ShopInvetoryManagement.BL;
using System.IO;

namespace BookShopManagement.Forms
{
    public partial class Employees : Form
    {
       
        Employee_Operation EMP = new Employee_Operation();
        // GET NEW ID 
        void GET_ID()
        {
            DataTable DT = new DataTable();
            DT = EMP.GET_EMP_ID();
            int id = Convert.ToInt32(DT.Rows[DT.Rows.Count - 1][0]);
            TXT_ID.Text = id.ToString();
        }
        public void JustNumber(KeyPressEventArgs r)
        {
            if (!char.IsDigit(r.KeyChar))
            {
                if (!char.IsControl(r.KeyChar))
                {
                    if (!char.IsPunctuation(r.KeyChar))
                    {
                        if (!char.IsWhiteSpace(r.KeyChar))
                        {
                            if (!char.IsSeparator(r.KeyChar))
                                r.Handled = true;
                        }
                    }
                }
            }
        }



        // visible tools text
        void tool_visible(Boolean G)
        {
            TXT_ID.Enabled = G;
            TXT_FIRST.Enabled = G;
            TXT_LAST.Enabled = G;
            TXT_IDENTITY.Enabled = G;
            TXT_AGE.Enabled = G;
            TXT_NOTE.Enabled = G;
            TXT_SALARY.Enabled = G;
            TXT_ADDRESS.Enabled = G;
            TXT_PHONE.Enabled = G;
            COMBO_JOB.Enabled = G;
            COMBO_SEX.Enabled = G;
            COMBO_STATUS.Enabled = G;
            DATE_HAIR.Enabled = G;

            EMP_PIC.Enabled = G;
            DOC1.Enabled = G;
            DOC2.Enabled = G;
            DOC3.Enabled = G;
            DOC4.Enabled = G;
            DOC5.Enabled = G;
            DOC6.Enabled = G;

        }

        // CLEAR TEXTBOX
        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);

           

            EMP_PIC.Image = ShopInvetoryManagement.Properties.Resources.photo;
            DOC1.Image = ShopInvetoryManagement.Properties.Resources._1;
            DOC2.Image = ShopInvetoryManagement.Properties.Resources._1;
            DOC3.Image = ShopInvetoryManagement.Properties.Resources._1;
            DOC4.Image = ShopInvetoryManagement.Properties.Resources._1;
            DOC5.Image = ShopInvetoryManagement.Properties.Resources._1;
            DOC6.Image = ShopInvetoryManagement.Properties.Resources._1;

                   }
        void grid_visible()
        {
            gridView1.Columns["ONE"].Visible = false;
            gridView1.Columns["TWO"].Visible = false;
            gridView1.Columns["THREE"].Visible = false;
            gridView1.Columns["FOUR"].Visible = false;
            gridView1.Columns["FIVE"].Visible = false;
            gridView1.Columns["SEX"].Visible = false;
        }
        public Employees()
        {
            InitializeComponent();
            // GET_ID();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            
        }

        private void BT_NEW_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            tool_visible(true);
            sqlDataSource1.Fill();
            GET_ID();
            BT_SAVE.Enabled = true;
            BT_NEW.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_DEL.Enabled = false;
            DATE_HAIR.Text = DateTime.Now.ToShortDateString();
        }

       
        private void BT_SAVE_Click(object sender, EventArgs e)
        {
            byte[] pictuer, DOC_1, DOC_2, DOC_3, DOC_4, DOC_5, DOC_6;
            if (EMP_PIC.Image == null)
            {
                pictuer = new byte[0];
                DOC_1 = new byte[0];
                DOC_2 = new byte[0];
                DOC_3 = new byte[0];
                DOC_4 = new byte[0];
                DOC_5 = new byte[0];
                DOC_6 = new byte[0];

                EMP.ADD_EMPLOYEE(Convert.ToInt16(TXT_ID.Text), TXT_FIRST.Text, TXT_LAST.Text, TXT_IDENTITY.Text, Convert.ToInt32(TXT_AGE.Text), COMBO_SEX.Text
                , COMBO_STATUS.Text, COMBO_JOB.Text, TXT_NOTE.Text, TXT_SALARY.Text, TXT_PHONE.Text,
                TXT_ADDRESS.Text, DATE_HAIR.DateTime.Date, pictuer, DOC_1, DOC_2, DOC_3, DOC_4, DOC_5, DOC_6, "without_image");

               
            }
            else
            {
                MemoryStream ms = new MemoryStream();
                MemoryStream D1 = new MemoryStream();
                MemoryStream D2 = new MemoryStream();
                MemoryStream D3 = new MemoryStream();
                MemoryStream D4 = new MemoryStream();
                MemoryStream D5 = new MemoryStream();
                MemoryStream D6 = new MemoryStream();

                EMP_PIC.Image.Save(ms, EMP_PIC.Image.RawFormat);
                pictuer = ms.ToArray();

                DOC1.Image.Save(D1, DOC1.Image.RawFormat);
                DOC_1 = D1.ToArray();

                DOC2.Image.Save(D2, DOC2.Image.RawFormat);
                DOC_2 = D2.ToArray();

                DOC3.Image.Save(D3, DOC3.Image.RawFormat);
                DOC_3 = D3.ToArray();

                DOC4.Image.Save(D4, DOC4.Image.RawFormat);
                DOC_4 = D4.ToArray();

                DOC5.Image.Save(D5, DOC5.Image.RawFormat);
                DOC_5 = D5.ToArray();

                DOC6.Image.Save(D6, DOC6.Image.RawFormat);
                DOC_6 = D6.ToArray();

                EMP.ADD_EMPLOYEE(Convert.ToInt16(TXT_ID.Text), TXT_FIRST.Text, TXT_LAST.Text, TXT_IDENTITY.Text, Convert.ToInt16 (TXT_AGE.Text), COMBO_SEX.Text
                    , COMBO_STATUS.Text, COMBO_JOB.Text, TXT_NOTE.Text, TXT_SALARY.Text, TXT_PHONE.Text,
                    TXT_ADDRESS.Text, DATE_HAIR.DateTime.Date, pictuer, DOC_1, DOC_2, DOC_3, DOC_4, DOC_5, DOC_6, "with_image");
            }


            MessageBox.Show("تم الحفظ بيانات الموظف", "عملية الإضافة", MessageBoxButtons.OK, MessageBoxIcon.Information);
            CLEAR_TEXT_BOX(this);
            sqlDataSource1.Fill();
            BT_SAVE.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_NEW.Enabled = true;
        }

        private void BT_DEL_Click(object sender, EventArgs e)
        {
            EMP.DELETE_EMP(Convert.ToInt16(TXT_ID.Text));
            MessageBox.Show("تم الحذف بنجاح", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Information);
            CLEAR_TEXT_BOX(this);
            sqlDataSource1.Fill();
            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = false;
        }

        private void BT_EDITE_Click(object sender, EventArgs e)
        {
           byte[] pictuer, DOC_1, DOC_2, DOC_3, DOC_4, DOC_5, DOC_6;
            if (EMP_PIC.Image == null)
            {
                pictuer = new byte[0];
                DOC_1 = new byte[0];
                DOC_2 = new byte[0];
                DOC_3 = new byte[0];
                DOC_4 = new byte[0];
                DOC_5 = new byte[0];
                DOC_6 = new byte[0];

                EMP.UPDATE_EMPLOYEE(Convert.ToInt16(TXT_ID.Text), TXT_FIRST.Text, TXT_LAST.Text, TXT_IDENTITY.Text, Convert.ToInt32(TXT_AGE.Text), COMBO_SEX.Text
                , COMBO_STATUS.Text, COMBO_JOB.Text, TXT_NOTE.Text, TXT_SALARY.Text, TXT_PHONE.Text,
                TXT_ADDRESS.Text, DATE_HAIR.DateTime.Date, pictuer, DOC_1, DOC_2, DOC_3, DOC_4, DOC_5, DOC_6, "without_image");


            }
            else
            {
                MemoryStream ms = new MemoryStream();
                MemoryStream D1 = new MemoryStream();
                MemoryStream D2 = new MemoryStream();
                MemoryStream D3 = new MemoryStream();
                MemoryStream D4 = new MemoryStream();
                MemoryStream D5 = new MemoryStream();
                MemoryStream D6 = new MemoryStream();

                EMP_PIC.Image.Save(ms, EMP_PIC.Image.RawFormat);
                pictuer = ms.ToArray();

                DOC1.Image.Save(D1, DOC1.Image.RawFormat);
                DOC_1 = D1.ToArray();

                DOC2.Image.Save(D2, DOC2.Image.RawFormat);
                DOC_2 = D2.ToArray();

                DOC3.Image.Save(D3, DOC3.Image.RawFormat);
                DOC_3 = D3.ToArray();

                DOC4.Image.Save(D4, DOC4.Image.RawFormat);
                DOC_4 = D4.ToArray();

                DOC5.Image.Save(D5, DOC5.Image.RawFormat);
                DOC_5 = D5.ToArray();

                DOC6.Image.Save(D6, DOC6.Image.RawFormat);
                DOC_6 = D6.ToArray();

                EMP.UPDATE_EMPLOYEE(Convert.ToInt16(TXT_ID.Text), TXT_FIRST.Text, TXT_LAST.Text, TXT_IDENTITY.Text, Convert.ToInt16(TXT_AGE.Text), COMBO_SEX.Text
                    , COMBO_STATUS.Text, COMBO_JOB.Text, TXT_NOTE.Text, TXT_SALARY.Text, TXT_PHONE.Text,
                    TXT_ADDRESS.Text, DATE_HAIR.DateTime.Date, pictuer, DOC_1, DOC_2, DOC_3, DOC_4, DOC_5, DOC_6, "with_image");
            }
                                   
            MessageBox.Show("تم التعديل بيانات الموظف", "عملية التعديل", MessageBoxButtons.OK, MessageBoxIcon.Information);
            CLEAR_TEXT_BOX(this);
            sqlDataSource1.Fill();
            BT_SAVE.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_DEL.Enabled = false;
        }

        private void BT_EXIT_Click(object sender, EventArgs e)
        {
            Dispose();
            Close();
        }

        private void Employees_Load(object sender, EventArgs e)
        {
            tool_visible(false);
            grid_visible();
            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = false;
        }

        private void EMP_PIC_DoubleClick(object sender, EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            ofd.Filter = "ملفات الصور |*.JPG;*.PNG;*.GIF;*.BMP";
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                EMP_PIC.Image = Image.FromFile(ofd.FileName);
            }
        }

        private void DOC1_DoubleClick(object sender, EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            ofd.Filter = "ملفات الصور |*.JPG;*.PNG;*.GIF;*.BMP";
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                DOC1.Image = Image.FromFile(ofd.FileName);
            }
        }

        private void DOC2_DoubleClick(object sender, EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            ofd.Filter = "ملفات الصور |*.JPG;*.PNG;*.GIF;*.BMP";
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                DOC2.Image = Image.FromFile(ofd.FileName);
            }
        }

        private void DOC3_DoubleClick(object sender, EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            ofd.Filter = "ملفات الصور |*.JPG;*.PNG;*.GIF;*.BMP";
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                DOC3.Image = Image.FromFile(ofd.FileName);
            }
        }

        private void DOC4_DoubleClick(object sender, EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            ofd.Filter = "ملفات الصور |*.JPG;*.PNG;*.GIF;*.BMP";
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                DOC4.Image = Image.FromFile(ofd.FileName);
            }
        }

        private void DOC5_DoubleClick(object sender, EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            ofd.Filter = "ملفات الصور |*.JPG;*.PNG;*.GIF;*.BMP";
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                DOC5.Image = Image.FromFile(ofd.FileName);
            }
        }

        private void DOC6_DoubleClick(object sender, EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            ofd.Filter = "ملفات الصور |*.JPG;*.PNG;*.GIF;*.BMP";
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                DOC6.Image = Image.FromFile(ofd.FileName);
            }
        }

        private void GRID_EMP_Click(object sender, EventArgs e)
        {
            if (gridView1.GetFocusedRowCellValue("رقم الموظف").ToString() is null)
            {
                return;
            }
            else
            {
                try
                {
                    tool_visible(true);
                    BT_EDITE.Enabled = true;
                    BT_DEL.Enabled = true;
                    BT_SAVE.Enabled = false;

                    TXT_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم الموظف"));
                    TXT_FIRST.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الإسم الأول"));
                    TXT_LAST.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الإسم الثاني"));
                    TXT_IDENTITY.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم الهوية"));
                    TXT_AGE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("العمر"));
                    COMBO_SEX.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("النوع"));
                    COMBO_STATUS.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الحالة الإجتماعية"));
                    COMBO_JOB.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("نوع الوظيفة"));
                    TXT_NOTE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الوصف"));
                    TXT_SALARY.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الراتب"));
                    TXT_PHONE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم الهاتف"));
                    TXT_ADDRESS.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("العنوان"));
                    DATE_HAIR.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("تاريخ التوظيف"));


                    byte[] pic = (byte[])gridView1.GetFocusedRowCellValue("صورة  الموضف");
                    MemoryStream MS = new MemoryStream(pic);
                    EMP_PIC.Image = Image.FromStream(MS);

                    byte[] pic1 = (byte[])gridView1.GetFocusedRowCellValue("ONE");
                    MemoryStream MS1 = new MemoryStream(pic1);
                    DOC1.Image = Image.FromStream(MS1);

                    byte[] pic2 = (byte[])gridView1.GetFocusedRowCellValue("TWO");
                    MemoryStream MS2 = new MemoryStream(pic2);
                    DOC2.Image = Image.FromStream(MS2);

                    byte[] pic3 = (byte[])gridView1.GetFocusedRowCellValue("THREE");
                    MemoryStream MS3 = new MemoryStream(pic3);
                    DOC3.Image = Image.FromStream(MS3);

                    byte[] pic4 = (byte[])gridView1.GetFocusedRowCellValue("FOUR");
                    MemoryStream MS4 = new MemoryStream(pic4);
                    DOC4.Image = Image.FromStream(MS4);

                    byte[] pic5 = (byte[])gridView1.GetFocusedRowCellValue("FIVE");
                    MemoryStream MS5 = new MemoryStream(pic5);
                    DOC5.Image = Image.FromStream(MS5);

                    byte[] pic6 = (byte[])gridView1.GetFocusedRowCellValue("SEX");
                    MemoryStream MS6 = new MemoryStream(pic6);
                    DOC6.Image = Image.FromStream(MS6);
                }
                catch
                {
                    return;
                }
            }
        }

        private void GRID_EMP_Click_1(object sender, EventArgs e)
        {
            GRID_EMP_Click(sender,  e);
        }

        private void TXT_SALARY_KeyPress(object sender, KeyPressEventArgs e)
        {
            JustNumber(e);
        }

        private void TXT_AGE_KeyPress(object sender, KeyPressEventArgs e)
        {
            JustNumber(e);
        }
    }
}