using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ShopInvetoryManagement.BL;


namespace BookShopManagement.Forms
{
    public partial class Form_AddCategory : Form
    {
        User_Operation ope = new User_Operation();
        void GET_ID()
        {
            DataTable DT = new DataTable();
            DT = ope.GET_Gate_ID();
            int id = Convert.ToInt32(DT.Rows[DT.Rows.Count - 1][0]);
            TXT_ID.Text = id.ToString();
        }
        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);
                    }

        public Form_AddCategory()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
               private void BT_NEW_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            GET_ID();
            BT_SAVE.Enabled = true;
            BT_DEL.Enabled = false;
            BT_NEW.Enabled = false;
           
        }

        private void BT_DEL_Click(object sender, EventArgs e)
        {
            ope.DELETE_GATE_DATA(Convert.ToInt16(TXT_ID.Text));
            MessageBox.Show("تم حذف بيانات الصنف ", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);
            BT_DEL.Enabled = false;
            BT_SAVE.Enabled = false;
            
        }

        private void Form_AddCategory_Load(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            BT_DEL.Enabled = false;
            BT_SAVE.Enabled = false;
            
           
        }
        void CHECK_CATE()
        {
            if (Program.Cate_ID == 0)
            {
               this.Close();
            }
            else
            {
                Program.Cate_ID = Program.Cate_ID + 1;
                Hide();
                using (Form_AddNewproduct ac = new Form_AddNewproduct())
                {

                    ac.ShowDialog();
                }
            }

        }
        private void BT_BACK_Click(object sender, EventArgs e)
        {
            CHECK_CATE();
        }

        private void BT_SAVE_Click(object sender, EventArgs e)
        {
            ope.ADD_GATE_DATA(Convert.ToInt16(TXT_ID.Text),TXT_NAME.Text,TXT_NOTE.Text);
            MessageBox.Show("تمت إضافة الصنف ", "عملية الإضافة", MessageBoxButtons.OK, MessageBoxIcon.Information);
            CLEAR_TEXT_BOX(this);
            sqlDataSource1.Fill();
            BT_SAVE.Enabled = false;
        }

        private void GRID_USER_Click(object sender, EventArgs e)
        {
            BT_DEL.Enabled = true;
           
            BT_SAVE.Enabled = false;

            CLEAR_TEXT_BOX(this);
            TXT_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم الصنف"));
            TXT_NAME.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم الصنف"));
            TXT_NOTE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("ملاحظة"));
        }

        private void Form_AddCategory_FormClosed(object sender, FormClosedEventArgs e)
        {
            Dispose();
        }
    }
}
