using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ShopInvetoryManagement.BL;
using System.Data.SqlClient;


namespace BookShopManagement.Forms
{

    public partial class Form_Bank_opreation : Form
    {
     public string RAD = "";
       Bank_Operation ope = new Bank_Operation();
        ShopInvetoryManagement.DAL.DATAACCESSLAYER DAL = new ShopInvetoryManagement.DAL.DATAACCESSLAYER();
        void GET_ID()
        {
            DataTable DT = new DataTable();
            DT = ope.GET_BankOPERATION_ID();
            int id = Convert.ToInt32(DT.Rows[DT.Rows.Count - 1][0]);
            TXT_ID.Text = id.ToString();
        }

        public void get_bankmoney()
        {
            string b_money, b_account;
            DataTable DT = ope.GetBank_Data_ONE(COMBO_BANK.Text);
            if (DT.Rows.Count > 0)
            {
                    b_account = DT.Rows[0]["Bank_Account"].ToString();
                    b_money = DT.Rows[0]["Bank_money"].ToString();
                    LBL_BANK_MONEY.Text = b_money;
                    LBL_ACC.Text = b_account;

                LBL_ACC.Visible = true;
                LBL_BANK_MONEY.Visible = true;
                label11.Visible = true;
                label2.Visible = true;
                
            }
        }
            public void COM_ID()
        {
            COMBO_BANK.DataSource = ope.GetBank_Data();
            COMBO_BANK.DisplayMember = "Bank_Name";
            COMBO_BANK.ValueMember = "Bank_ID";

        }
        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);
            TXT_EMP.Text = Program.Casheir;
           
        }

        public Form_Bank_opreation()
        {
            InitializeComponent();
            TXT_EMP.Text = Program.Casheir;
            DATE_OPE.Text = DateTime.Now.ToLongDateString();
            BT_SAVE.Enabled = false;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource

        }

        private void Form_Bank_opreation_Load(object sender, EventArgs e)
        {
            
            COM_ID();
             BT_SAVE.Enabled = false;
           
        }
        public void JustNumber(KeyPressEventArgs r)
        {
            if (!char.IsDigit(r.KeyChar))
            {
                if (!char.IsControl(r.KeyChar))
                {
                    if (!char.IsPunctuation(r.KeyChar))
                    {
                        if (!char.IsWhiteSpace(r.KeyChar))
                        {
                            if (!char.IsSeparator(r.KeyChar))
                                r.Handled = true;
                        }
                    }
                }
            }
        }

        void SOLAFA(Boolean SOL)
        {
            RADTRANSFER.Enabled = SOL;
            RAD_SUPLLING.Enabled = SOL;
            RAD_CASH.Enabled = SOL;
            TXT_BYAN.Enabled = SOL;
            TXT_MONEY.Enabled = SOL;
            TXT_NAME1.Enabled = SOL;
            TXT_NAME2.Enabled = SOL;
            TXT_NOTE.Enabled = SOL;
        }
        private void BT_NEW_Click(object sender, EventArgs e)
        {
            DATE_OPE.Text = DateTime.Now.ToShortDateString();
            SOLAFA(true);
            CLEAR_TEXT_BOX(this);
            GET_ID();
            COM_ID();
            get_bankmoney();
            BT_SAVE.Enabled = true;
            BT_NEW.Enabled = false;
           
        }

        ////private void BT_DEL_Click(object sender, EventArgs e)
        ////{
        ////    ope.DELETE_BANK_OPERATION(Convert.ToInt16(TXT_ID.Text));
        ////    MessageBox.Show("تم حذف المعاملة ", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Information);
        ////    CLEAR_TEXT_BOX(this);
           
        ////    BT_SAVE.Enabled = false;
        ////}

        private void BT_BACK_Click(object sender, EventArgs e)
        {
            Dispose();
            Close();
        }

        private void RAD_CASH_CheckedChanged(object sender, EventArgs e)
        {
            TXT_NAME1.Visible = false;
            TXT_NAME2.Visible = false;
            label7.Visible = false;
            label8.Visible = false;
            RAD = "سحب";
            RADTRANSFER.Visible = false;
            RADTRANSFER.Checked = false;
            RAD_SUPLLING.Visible = false;
            RAD_SUPLLING.Checked = false;
            //MessageBox.Show(RAD);
        }

        private void RAD_SUPLLING_CheckedChanged(object sender, EventArgs e)
        {
            TXT_NAME1.Visible = true;
            TXT_NAME2.Visible = true;
            label7.Visible = true;
            label8.Visible = true;
            label7.Text = "المورد منه";
            label8.Text = "المورد إليه";
            RAD = "توريد";
            RAD_CASH.Visible = false;
            RAD_CASH.Checked = false;
            RADTRANSFER.Visible = false;
            RADTRANSFER.Checked = false;
           // MessageBox.Show(RAD);
        }

        private void RADTRANSFER_CheckedChanged(object sender, EventArgs e)
        {
            label7.Text = "المحول منه";
            label8.Text = "المحول إليه";
            TXT_NAME1.Visible = true;
            TXT_NAME2.Visible = true;
            label7.Visible = true;
            label8.Visible = true;
            RAD = "تحويل";
            RAD_CASH.Visible = false;
            RAD_CASH.Checked = false;
            RAD_SUPLLING.Visible = false;
            RAD_SUPLLING.Checked = false;
          //  MessageBox.Show(RAD);

        }
       
        private void BT_SAVE_Click(object sender, EventArgs e)
        {
            if (TXT_MONEY.Text == "" || TXT_ID.Text == "" || TXT_NAME1.Text == " " || TXT_NAME2.Text == "" || TXT_BYAN.Text == "")
            {
                MessageBox.Show("الرجاء ملء الحقول");
                return;
            }
            
            if (RAD == "سحب")
                {
                if (Convert.ToDecimal(TXT_MONEY.Text) > Convert.ToDecimal(LBL_BANK_MONEY.Text))
                {
                    MessageBox.Show("هذا المبلغ غير متوفر حالياً");
                    return;
                }
                var M = Convert.ToDecimal(LBL_BANK_MONEY.Text) - Convert.ToDecimal( TXT_MONEY.Text);
                    TXT_NAME1.Text = "بدون إسم";
                    TXT_NAME2.Text = "بدون إسم";
                ope.ADD_BANKOPERATION(Convert.ToInt16(TXT_ID.Text), Convert.ToInt16(COMBO_BANK.SelectedValue), Program.Casheir_ID, TXT_NAME1.Text, TXT_NAME2.Text, TXT_MONEY.Text, RAD, TXT_BYAN.Text, TXT_NOTE.Text, DATE_OPE.DateTime.Date,LBL_BANK_MONEY.Text,M.ToString());
                ope.CONFIQ_Bank_MONEY(COMBO_BANK.Text, TXT_MONEY.Text, "ONE");
                LBL_BANK_MONEY.Text = M.ToString();
                RAD_CASH.Checked = false;
            }
               else if (RAD == "توريد")
                {
                var M = Convert.ToDecimal(LBL_BANK_MONEY.Text) + Convert.ToDecimal(TXT_MONEY.Text);
                ope.ADD_BANKOPERATION(Convert.ToInt16(TXT_ID.Text), Convert.ToInt16(COMBO_BANK.SelectedValue), Program.Casheir_ID, TXT_NAME1.Text, TXT_NAME2.Text, TXT_MONEY.Text, RAD, TXT_BYAN.Text, TXT_NOTE.Text, DATE_OPE.DateTime.Date,LBL_BANK_MONEY.Text, M.ToString());
                ope.CONFIQ_Bank_MONEY(COMBO_BANK.Text, TXT_MONEY.Text, "TWO");
                LBL_BANK_MONEY.Text = M.ToString();
                RAD_SUPLLING.Checked = false;
            }
                else
                {
                if (Convert.ToDecimal(TXT_MONEY.Text) > Convert.ToDecimal(LBL_BANK_MONEY.Text))
                {
                    MessageBox.Show("هذا المبلغ غير متوفر حالياً");
                    return;
                }
                var M = Convert.ToDecimal(LBL_BANK_MONEY.Text) - Convert.ToDecimal(TXT_MONEY.Text);
                ope.ADD_BANKOPERATION(Convert.ToInt16(TXT_ID.Text), Convert.ToInt16(COMBO_BANK.SelectedValue), Program.Casheir_ID, TXT_NAME1.Text, TXT_NAME2.Text, TXT_MONEY.Text, RAD, TXT_BYAN.Text, TXT_NOTE.Text, DATE_OPE.DateTime.Date,LBL_BANK_MONEY.Text,M.ToString());
                ope.CONFIQ_Bank_MONEY(COMBO_BANK.Text, TXT_MONEY.Text, "ONE");
                LBL_BANK_MONEY.Text = M.ToString();
                RADTRANSFER.Checked = false;
            }

                MessageBox.Show("تمت إضافة المعاملة ", "عملية الإضافة", MessageBoxButtons.OK, MessageBoxIcon.Information);
                CLEAR_TEXT_BOX(this);
                BT_NEW.Enabled = true;
                BT_SAVE.Enabled = false;
                RAD_CASH.Visible = true;
                RAD_SUPLLING.Visible = true;
                RADTRANSFER.Visible = true;
                SOLAFA(false);
                DATE_OPE.Text = DateTime.Now.ToLongDateString();
        }

        ////private void BT_EDIT_Click(object sender, EventArgs e)
        ////{
        ////    if (TXT_MONEY.Text == "" || TXT_ID.Text == "")
        ////    {
        ////        return;
        ////    }

        ////    if (RAD == "سحب")
        ////    {
        ////        TXT_NAME1.Text = "بدون إسم";
        ////        TXT_NAME2.Text = "بدون إسم";
        ////        ope.EDIT_BANKOPERATION(Convert.ToInt16(TXT_ID.Text), Convert.ToInt16(COMBO_BANK.SelectedValue), F.log_id, TXT_NAME1.Text, TXT_NAME2.Text, TXT_MONEY.Text, RAD, TXT_BYAN.Text, TXT_NOTE.Text, DATE_OPE.DateTime.Date);
        ////    }
        ////    else if (RAD == "توريد")
        ////    {
        ////        ope.EDIT_BANKOPERATION(Convert.ToInt16(TXT_ID.Text), Convert.ToInt16(COMBO_BANK.SelectedValue), F.log_id, TXT_NAME1.Text, TXT_NAME2.Text, TXT_MONEY.Text, RAD, TXT_BYAN.Text, TXT_NOTE.Text, DATE_OPE.DateTime.Date);
        ////    }
        ////    else
        ////    {
        ////        ope.EDIT_BANKOPERATION(Convert.ToInt16(TXT_ID.Text), Convert.ToInt16(COMBO_BANK.SelectedValue), F.log_id, TXT_NAME1.Text, TXT_NAME2.Text, TXT_MONEY.Text, RAD, TXT_BYAN.Text, TXT_NOTE.Text, DATE_OPE.DateTime.Date);
        ////    }

        ////    MessageBox.Show("تمت تعديل المعاملة ", "عملية التعديل", MessageBoxButtons.OK, MessageBoxIcon.Information);
        ////    CLEAR_TEXT_BOX(this);
        ////    BT_NEW.Enabled = true;
        ////    BT_SAVE.Enabled = false;
        ////           }

        //////private void GRID_Bank_Ope_Click(object sender, EventArgs e)
        //////{
        //////    SOLAFA(true);
        //////    BT_NEW.Enabled = true;
        //////    BT_SAVE.Enabled = true;
        //////    BT_EDIT.Enabled = true;
        //////    BT_SAVE.Enabled = false;
        //////    string OPE_TYPE;
            
        //////    try
        //////    {
        //////       TXT_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم المعاملة"));
        //////        TXT_EMP.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم الموظف"));
        //////       TXT_BYAN.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("البيان"));
        //////        TXT_NOTE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("ملاحظة"));
        //////       TXT_MONEY.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("المبلغ"));
        //////        TXT_NAME1.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("المستفيد الأول"));
        //////        TXT_NAME2.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("المستفيد الثاني"));
        //////        COMBO_BANK.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم البنك"));
        //////       DATE_OPE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("التاريخ"));
        //////        OPE_TYPE = Convert.ToString(gridView1.GetFocusedRowCellValue("نوع المعاملة"));
        //////        COMBO_BANK.Refresh();
               

        //////        if (OPE_TYPE == "سحب")
        //////        {
        //////            RAD_CASH.Checked = true;
        //////            RAD_CASH.Visible = true;

        //////            TXT_NAME1.Visible = false;
        //////            TXT_NAME2.Visible = false;
        //////            label7.Visible = false;
        //////            label8.Visible = false;
        //////            RADTRANSFER.Visible = false;
        //////            RADTRANSFER.Checked = false;
        //////            RAD_SUPLLING.Visible = false;
        //////            RAD_SUPLLING.Checked = false;
        //////        }
        //////        else if(OPE_TYPE == "توريد")
        //////        {
        //////            RAD_SUPLLING.Checked = true;
        //////            RAD_SUPLLING.Visible = true;

        //////            TXT_NAME1.Visible = true;
        //////            TXT_NAME2.Visible = true;
        //////            label7.Visible = true;
        //////            label8.Visible = true;
        //////            label7.Text = "المورد منه";
        //////            label8.Text = "المورد إليه";
        //////            RAD_CASH.Visible = false;
        //////            RAD_CASH.Checked = false;
        //////            RADTRANSFER.Visible = false;
        //////            RADTRANSFER.Checked = false;
        //////        }
        //////        else
        //////        {
        //////            RADTRANSFER.Checked = true;
        //////            RADTRANSFER.Visible = true;

        //////            label7.Text = "المحول منه";
        //////            label8.Text = "المحول إليه";
        //////            TXT_NAME1.Visible = true;
        //////            TXT_NAME2.Visible = true;
        //////            label7.Visible = true;
        //////            label8.Visible = true;
        //////            RAD_CASH.Visible = false;
        //////            RAD_CASH.Checked = false;
        //////            RAD_SUPLLING.Visible = false;
        //////            RAD_SUPLLING.Checked = false;
        //////        }
        //////        sqlDataSource1.Fill();
        //////    }
        //////    catch
        //////    {
        //////        return;
        //////    }
        //////}

        private void COMBO_BANK_SelectedIndexChanged(object sender, EventArgs e)
        {
            get_bankmoney();
        }

        private void TXT_MONEY_KeyUp(object sender, KeyEventArgs e)
        {
            
        }

        private void panel8_Paint(object sender, PaintEventArgs e)
        {

        }

        private void TXT_MONEY_KeyPress(object sender, KeyPressEventArgs e)
        {
            JustNumber(e);
        }

        //private void TXT_MONEY_KeyPress(object sender, KeyPressEventArgs e)
        //{

        //}
    }
}
