using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ShopInvetoryManagement.BL;

namespace BookShopManagement.Forms
{
    public partial class Form_AddStock : Form
    {
        private static Form_AddStock frm;
        static void frm_formClosed(object sender, FormClosedEventArgs e)
        {
            frm = null;
        }

        public static Form_AddStock getMainForm
        {
            get
            {
                if (frm == null)
                {
                    frm = new Form_AddStock();
                    frm.FormClosed += new FormClosedEventHandler(frm_formClosed);
                }
                return frm;
            }
        }


        public Form_AddStock()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            if (frm == null)
                frm = this;
            sqlDataSource1.Fill();
        }

        private void button3_Click(object sender, EventArgs e)
        {
            this.Dispose();
        }
       public string i, y;

        private void BT_EDIT_Click(object sender, EventArgs e)
        {
            try
            {
                Form_AddNewproduct FRM = new Form_AddNewproduct();
                FRM.TXT_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم المنتج"));
                FRM.TXT_BARCODE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("باركود المنتج"));
                FRM.TXT_NAME.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم المنتج"));
                FRM.TXT_QUAN.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("كمية المخزن"));
                FRM.TXT_NOTE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الوصف"));
                FRM.COMBO_CAT.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الصنف"));
                FRM.TXT_PRICE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("سعر الشراء"));
                FRM.TXT_TAJZA_PRICE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("سعر بيع التجزئة"));
                FRM.TXT_JUOMLA_PRICE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("سعر بيع الجملة"));
                FRM.TXT_STOCK_NO.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم المستودع"));
                FRM.DATE_ENTER.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("التاريخ"));

              
                y = Convert.ToString(gridView1.GetFocusedRowCellValue("باركود المنتج"));

                FRM.COM_ID();
                FRM.Text = " تعديل المنتج :" + " " + Convert.ToString(gridView1.GetFocusedRowCellValue("إسم المنتج"));
                FRM.BT_SAVE.Text = "تعديل";
                FRM.state = "EDIT";
                FRM.TXT_ID.ReadOnly = true;
                FRM.BT_NEW.Enabled = false;
               

                FRM.ShowDialog(this);

                sqlDataSource1.Fill();

            }
            catch
            {
                return;
            }
        
    }

        private void BT_NEW_Click(object sender, EventArgs e)
        {
            Form_AddNewproduct frm = new Form_AddNewproduct();
            frm.ShowDialog(this);
            sqlDataSource1.Fill();
        }

        private void BT_BACK_Click(object sender, EventArgs e)
        {
            Dispose();
            Close();
        }

        private void GRID_CUSTOMER_Click(object sender, EventArgs e)
        {
            i = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم المنتج"));
        }

        private void TXT_BARCODE_TextChanged(object sender, EventArgs e)
        {

        }

        private void BT_DEL_Click(object sender, EventArgs e)
        {
            //if (i   == "")
            //{
            //    return;
            //}

            if (MessageBox.Show("هل تريد حذف المنتج المحدد!", "عملية الحذف", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
            {
                Product_Operation ope = new Product_Operation();
                ope.DELETE_PRODUCTS(Convert.ToInt16(i));
                MessageBox.Show("تم حذف المنتج بنجاح", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Information);
                sqlDataSource1.Fill();
            }
            else
            {
                MessageBox.Show("تم إلغاء عملية الحذف", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
        }
    }
}
