using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BookShopManagement.Forms;
using ShopInvetoryManagement.Forms;
using ShopInvetoryManagement.BL;

namespace ShopInvetoryManagement.Forms
{
    public partial class User_Permiastion : Form
    {
        User_Operation USE = new User_Operation();
        int log_id;
        Boolean  C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16;

        private void button2_Click(object sender, EventArgs e)
        {
            BT_EDITE.Enabled = false;
            BT_DEL.Enabled = false;
           // BT_SAVE.Enabled = true;
            COMBO_NAME.Enabled = true;
            groupBox1.Enabled = true;
            bt_new.Enabled = false;
        }

        public void COM_ID()
        {
            COMBO_NAME.DataSource = USE.get_user_name();
            COMBO_NAME.DisplayMember = "EMB_NAME";
            COMBO_NAME.ValueMember = "User_ID";

            DataTable DT = USE.get_user_name();
            log_id = Convert.ToInt16(DT.Rows[0]["User_ID"]);
        }
        void SOLAFA(Boolean SOLA)
        {
            C_BAC_RES.Checked = SOLA;
            C_BILLS.Checked = SOLA;
            C_BANK.Checked = SOLA;
            C_BANK_OPE.Checked = SOLA;
            C_CATE.Checked = SOLA;
            C_CUST.Checked = SOLA;
            C_CUS_PAY.Checked = SOLA;
            C_DIEON.Checked = SOLA;
            C_EMP.Checked = SOLA;
            C_PERM.Checked = SOLA;
            C_POS.Checked = SOLA;
            C_PRD.Checked = SOLA;
            C_SHECK.Checked = SOLA;
            C_STG_OPE.Checked = SOLA;
            C_STOCK.Checked = SOLA;
            C_STORAGE.Checked = SOLA;
            COMBO_NAME.Enabled = SOLA;
            groupBox1.Enabled = SOLA;
           // BT_SAVE.Enabled = SOLA;
            BT_EDITE.Enabled = SOLA;
            BT_DEL.Enabled = SOLA;
        }

        public User_Permiastion()
        {
            InitializeComponent();
            COM_ID();
            SOLAFA(false);
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        StringBuilder str = new StringBuilder();       
        private void BT_BACK_Click_1(object sender, EventArgs e)
        {
            Dispose();
            Close();
        }

        private void COMBO_NAME_SelectedIndexChanged(object sender, EventArgs e)
        {
            //MessageBox.Show(log_id.ToString());
            COMBO_NAME.Enabled = false;
        }

        private void BT_EDITE_Click(object sender, EventArgs e)
        {
            if (C_BILLS.Checked == true)
            {
                C1 = true;
            }
            else
            {
                C1 = false;
            }

            if (C_CUST.Checked == true)
            {
                C2 = true;
            }
            else
            {
                C2 = false;
            }

            if (C_CUS_PAY.Checked == true)
            {
                C3 = true;
            }
            else
            {
                C3 = false;
            }
            if (C_DIEON.Checked == true)
            {
                C4 = true;
            }
            else
            {
                C4 = false;
            }

            if (C_EMP.Checked == true)
            {
                C5 = true;
            }
            else
            {
                C5 = false;
            }
            if (C_CATE.Checked == true)
            {
                C6 = true;
            }
            else
            {
                C6 = false;
            }
            if (C_PRD.Checked == true)
            {
                C7 = true;
            }
            else
            {
                C7 = false;
            }
            if (C_STOCK.Checked == true)
            {
                C8 = true;
            }
            else
            {
                C8 = false;
            }
            if (C_BANK.Checked == true)
            {
                C9 = true;
            }
            else
            {
                C9 = false;
            }
            if (C_BANK_OPE.Checked == true)
            {
                C10 = true;
            }
            else
            {
                C10 = false;
            }
            if (C_STORAGE.Checked == true)
            {
                C11 = true;
            }
            else
            {
                C11 = false;
            }
            if (C_STG_OPE.Checked == true)
            {
                C12 = true;
            }
            else
            {
                C12 = false;
            }
            if (C_SHECK.Checked == true)
            {
                C13 = true;
            }
            else
            {
                C13 = false;
            }
            if (C_POS.Checked == true)
            {
                C14 = true;
            }
            else
            {
                C14 = false;
            }
            if (C_PERM.Checked == true)
            {
                C15 = true;
            }
            else
            {
                C15 = false;
            }
            if (C_BAC_RES.Checked == true)
            {
                C16 = true;
            }
            else
            {
                C16 = false;
            }
            USE.UBDATE_USER_PERMISITION(log_id, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16);


            MessageBox.Show("تم تعديل صلاحيات المستخدم ", "عملية التعديل", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();
      
            COMBO_NAME.SelectedText = " ";
           // BT_SAVE.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_DEL.Enabled = false;
            SOLAFA(false);
        }

        private void BT_DEL_Click(object sender, EventArgs e)
        {
            C1 = false;
                       C2 = false;
                        C3 = false;
                        C4 = false;
                        C5 = false;
                        C6 = false;
                        C7 = false;
                        C8 = false;
                        C9 = false;
                      C10 = false;
                        C11 = false;
                       C12 = false;
                        C13 = false;
                      C14 = false;
                     C15 = false;
                      C16 = false;

            USE.UBDATE_USER_PERMISITION(log_id, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16);
            MessageBox.Show("تم حذف صلاحيات المستخدم ", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();

            COMBO_NAME.SelectedText = "";
            BT_DEL.Enabled = false;
           // BT_SAVE.Enabled = false;
            BT_EDITE.Enabled = false;
            SOLAFA(false);
        }

        private void GRID_PERMISITION_Click(object sender, EventArgs e)
        {
          //  BT_SAVE.Enabled = false;
            BT_EDITE.Enabled = true;
            BT_DEL.Enabled = true;
            bt_new.Enabled = true;
            groupBox1.Enabled = true;
            COMBO_NAME.Enabled = true;
            try
            {
                COMBO_NAME.Text = " ";
            
            log_id  =Convert .ToInt32 ( gridView1.GetFocusedRowCellValue("رقم المستخدم"));
                C_BAC_RES.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("قاعدة البيانات"));
                C_BILLS.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("المصروفات"));
                C_CUST.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("إضافة العملاء"));
                C_CUS_PAY.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("دفعات العملاء"));
                C_DIEON.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("الديون"));

                C_EMP.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("إضافة الموظفين"));
                C_PERM.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("صلاحيات المستخدمين"));
                C_POS.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("نافذة البيع"));
                C_PRD .Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("المنتجات"));
                C_SHECK.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("الشيكات"));

                C_STG_OPE.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("معاملات الخزنة"));
                C_STOCK.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("إدارة المخزن"));
                C_STORAGE.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("إضافة الخزنة"));
                C_BANK.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("إضافة البنوك"));
                C_BANK_OPE.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("معاملات البنك"));
                C_CATE.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("الأصناف"));

                COMBO_NAME.SelectedText = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم المستخدم"));


            }
            catch
            {
                return;
            }
        }
    }
}
