using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ShopInvetoryManagement.BL;

namespace BookShopManagement.Forms
{
    public partial class UserForm : Form
    {
        User_Operation ope = new User_Operation();
        void GET_ID()
        {
            DataTable DT = new DataTable();
            DT = ope.GET_User_ID();
            int id = Convert.ToInt32(DT.Rows[DT.Rows.Count - 1][0]);
            TXT_ID.Text = id.ToString();
        }

        public void COM_ID()
        {
            COMBO_EMP.DataSource = ope.GET_EMP_FULLNAME();
            COMBO_EMP.DisplayMember = "FULLNAME";
            COMBO_EMP.ValueMember = "Emp_ID";

        }

        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);

        }
        public UserForm()
        {
            InitializeComponent();
            fill_grid();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //sqlDataSource1.Fill();
        }

        private void BT_SAVE_Click(object sender, EventArgs e)
        {
            if (TXT_NAME.Text == string.Empty || TXT_PASS.Text == string.Empty || TXT_CONFIQ.Text == string.Empty || COMBO_TYPE.Text == string.Empty)
            {
                MessageBox.Show("يجب إدخال جميع البيانات", "الحقول فارقة", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            if (TXT_CONFIQ.Text != TXT_PASS.Text)
            {
                MessageBox.Show("كلمة المرور غير متطابقة ", "خطأ في التحقق", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }


            ope.ADD_USER(Convert.ToInt16(TXT_ID.Text),COMBO_TYPE.Text,TXT_NAME.Text,TXT_PASS.Text,Convert.ToInt32(COMBO_EMP.SelectedValue));
            MessageBox.Show("تمت إضافة المستخدم بنجاح", "عملية الإضافة", MessageBoxButtons.OK, MessageBoxIcon.Information);
            fill_grid();
            // sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);
            COMBO_EMP.Text = "";
            COMBO_TYPE.Text = "";
            BT_SAVE.Enabled = false;
            BT_EDIT.Enabled = false;
            BT_DEL.Enabled = false;
        }

        private void BT_NEW_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            COMBO_EMP.Text = "";
            COMBO_TYPE.Text = "";

            GET_ID();
            COM_ID();
            BT_SAVE.Enabled = true;
            BT_DEL.Enabled = false;
            BT_EDIT.Enabled = false;
        }

        private void BT_EDIT_Click(object sender, EventArgs e)
        {
            if (TXT_NAME.Text == string.Empty || TXT_PASS.Text == string.Empty || TXT_CONFIQ.Text == string.Empty || COMBO_TYPE.Text == string.Empty)
            {
                MessageBox.Show("يجب إدخال جميع البيانات", "الحقول فارقة", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            if (TXT_CONFIQ.Text != TXT_PASS.Text)
            {
                MessageBox.Show("كلمة المرور غير متطابقة ", "خطأ في التحقق", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }


            ope.EDIT_USER(Convert.ToInt16(TXT_ID.Text), COMBO_TYPE.Text, TXT_NAME.Text, TXT_PASS.Text, Convert.ToInt32(COMBO_EMP.SelectedValue));
            MessageBox.Show("تم تعديل بيانات المستخدم ", "عملية التعديل", MessageBoxButtons.OK, MessageBoxIcon.Information);
            fill_grid();
            // sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);
            COMBO_EMP.Text = "";
            COMBO_TYPE.Text = "";
            BT_SAVE.Enabled = false;
            BT_EDIT.Enabled = false;
            BT_DEL.Enabled = false;
        }

        private void BT_DEL_Click(object sender, EventArgs e)
        {
            ope.DELETE_USER(Convert.ToInt16(TXT_ID.Text));
            MessageBox.Show("تم حذف بيانات المستخدم ", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Information);
            fill_grid();
            // sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);
            COMBO_EMP.Text = "";
            COMBO_TYPE.Text = "";
            BT_DEL.Enabled = false;
            BT_SAVE.Enabled = false;
            BT_EDIT.Enabled = false;
        }
        void fill_grid()
        {
            if (Program.ISuser == true)
            {
                DataTable DT= new DataTable();
                DT = ope.for_user(Program.Casheir_ID);
                GRID_USER.DataSource = DT;

                BT_DEL.Enabled = false;
                BT_NEW.Enabled = false;
                BT_SAVE.Enabled = false;
                BT_EDIT.Enabled = false;
                // COMBO_TYPE.Enabled = false;
            }
            else
            {
                sqlDataSource1.Fill();
            }
        }
        private void UserForm_Load(object sender, EventArgs e)
        {
            fill_grid();
            CLEAR_TEXT_BOX(this);
            COMBO_EMP.Text = "";
            COMBO_TYPE.Text = "";
            BT_DEL.Enabled = false;
            BT_EDIT.Enabled = false;
            BT_SAVE.Enabled = false;
        }

        private void GRID_USER_Click(object sender, EventArgs e)
        {
            if (Program.ISuser == true)
            {
                BT_EDIT.Enabled = true;
            }
            else
            {
                BT_SAVE.Enabled = false;
                BT_EDIT.Enabled = true;
                BT_DEL.Enabled = true;
            }
            
            try
            {
                CLEAR_TEXT_BOX(this);
                COMBO_EMP.Text  = "";
                COMBO_TYPE.Text  = "";

                TXT_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("رقم المستخدم"));
                TXT_NAME.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم المستخدم"));
                TXT_PASS.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("كلمة المرور"));
                TXT_CONFIQ.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("كلمة المرور"));
                COMBO_TYPE.Text  = Convert.ToString(gridView1.GetFocusedRowCellValue("نوع المستخدم"));
                string SD = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم الموظف"));
                COMBO_EMP.Text  = SD;
            }
            catch
            {
                return;
            }
        }

        private void BT_EXIT_Click(object sender, EventArgs e)
        {
            Dispose();
            Close();

        }
    }
}
